(define (problem strips-robot)
    (:domain robot-strips)
    (:objects room_0_0 room_0_1 room_1_0 room_1_1)
    (:init (at room_0_0)
           (connected room_0_0 room_0_1)
           (connected room_0_1 room_0_0)
           (connected room_1_0 room_1_1)
           (connected room_1_1 room_1_0)
           (connected room_0_0 room_1_0)
           (connected room_1_0 room_0_0)
           (connected room_0_1 room_1_1)
           (connected room_1_1 room_0_1)
    )
    (:goal (and (at room_1_1)))
)